### ISSUE TITLE
🆕 Unicode 11

### ISSUE THREAD

**Issue by alvinlindstam** [SamCB/Emoji2Text#1]
Nice package! Just wanted to let you know that https://github.com/alvinlindstam/grapheme is updated for Unicode 11, in case it helps you stay up to date on your emojis  :)

**Comment by SamCB** [comment]
Thanks for this. I'm going to close this cause I'm so slow it's well and truly beyond the time to switch to Unicode 12 in #2. Thanks for your library by the way. Indispensable.
